# Dockerfile to create OpenMandriva Lx 4.0/cooker base images
# Create base image with mkimage-dnf.sh script
#

FROM scratch
MAINTAINER "Alexander Stefanov-Khryukin" <alexander@mezon.ru>
ADD rootfs-cooker.tar.xz /
