# Dockerfile to create OpenMandriva Lx 4.3/cooker base images
# Create base image with mkimage-dnf.sh script
#

FROM scratch
MAINTAINER Bernhard Rosenkraenzer <bero@lindev.ch>
ADD rootfs-4.3.tar.xz /
