# Dockerfile to create OpenMandriva Lx 4.2/cooker base images
# Create base image with mkimage-dnf.sh script
#

FROM scratch
MAINTAINER Bernhard Rosenkraenzer <bero@lindev.ch>
ADD rootfs-4.2.tar.xz /
