# Dockerfile to create OpenMandriva linux 2014 base images
# Create base image with mkimage-urpmi.sh script
#

FROM scratch
MAINTAINER "Alexander Stefanov-Khryukin" <alexander@mezon.ru>
ADD rootfs-2014.1.tar.xz /
