# Dockerfile to create OpenMandriva linux LX3 base images
# Create base image with mkimage-urpmi.sh script
#

FROM scratch
MAINTAINER "Alexander Stefanov-Khryukin" <alexander@mezon.ru>
ADD rootfs-4.0.tar.xz /
