# Dockerfile to create OpenMandriva Lx rock/rolling/cooker base images
# Create base image with mkimage-dnf.sh script
#

FROM scratch

ARG INSTALL_VERSION=cooker
LABEL maintainer="Alexander Stefanov <alexander@mezon.ru>"
ADD rootfs-${INSTALL_VERSION}.tar.xz /
